image: debian:stable-slim

stages:
  - test

.shell_test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends bash dash git ksh zsh ca-certificates util-linux
    - tests/setup.sh
  script:
    - SHELL_UNDER_TEST="${SHELL_UNDER_TEST}" tests/run.sh

test:bash:
  extends: .shell_test
  variables:
    SHELL_UNDER_TEST: bash

test:dash:
  extends: .shell_test
  variables:
    SHELL_UNDER_TEST: dash

test:zsh:
  extends: .shell_test
  variables:
    SHELL_UNDER_TEST: zsh

test:ksh:
  extends: .shell_test
  variables:
    SHELL_UNDER_TEST: ksh
